

affiche_mat:
    path:     /AfficheMatrs
    defaults: { _controller: MatiereBundle:Matiere:affiche }

ajouterMat:
    path:     /AjouterMat
    defaults: { _controller: MatiereBundle:Matiere:ajouter }

suppMat:
    path : /SupprimerMat/{numMat}
    defaults : {_controller : MatiereBundle:Matiere:supprimer}


edit_matiere:
    path:  /EditMat/{numMat}
    defaults: { _controller: MatiereBundle:Matiere:edit }