absence:
    resource: "@AbsenceBundle/Resources/config/routing.yml"
    prefix:   /

classe:
    resource: "@ClasseBundle/Resources/config/routing.yml"
    prefix:   /

matiere:
    resource: "@MatiereBundle/Resources/config/routing.yml"
    prefix:   /

note:
    resource: "@NoteBundle/Resources/config/routing.yml"
    prefix:   /

eleve:
    resource: "@EleveBundle/Resources/config/routing.yml"
    prefix:   /

personne:
    resource: "@PersonneBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
