
NbMaitre:
    path:     /
    defaults: { _controller: PersonneBundle:Personne:NbMaitre }


affichePers:
    path:     /AffichePers
    defaults: { _controller: PersonneBundle:Personne:affiche }

ajouterPers:
    path : /AjouterPer
    defaults : {_controller : PersonneBundle:Personne:ajouter}

suppPers:
    path : /SupprimerPer/{cin}
    defaults : {_controller : PersonneBundle:Personne:supprimer}


edit_personne:
    path : /EditPers/{cinPersonne}
    defaults : {_controller : PersonneBundle:Personne:edit}



dashboard_homepage:
    path : /
    defaults : {_controller : PersonneBundle:Personne:Dashboard}

login:
    path : /login
    defaults : {_controller : PersonneBundle:Personne:login}

