

classe_affichage:
    path:   /Afficheclasse
    defaults: { _controller: ClasseBundle:Classe:affiche }

ajouter_classe:
    path:     /Ajouterclasse
    defaults: { _controller:ClasseBundle:Classe:ajouter }

supp_classe:
    path : /Supprimerclasse/{num}
    defaults : {_controller : ClasseBundle:Classe:supprimer}

edit_classe:
        path:  /Editclasse/{num}
        defaults: { _controller: ClasseBundle:Classe:edit }