
affiche_eleve:
    path:     /AfficheElevs
    defaults: { _controller: EleveBundle:Eleve:affiche }

ajouterElev:
    path:     /AjouterElev
    defaults: { _controller: EleveBundle:Eleve:ajouter }

suppElvs:
    path : /SupprimerElv/{num}
    defaults : {_controller : EleveBundle:Eleve:supprimer}

edit_eleve:
    path:  /EditElevs/{num}
    defaults: { _controller: EleveBundle:Eleve:edit }
