<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLda6qhs\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLda6qhs/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerLda6qhs.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerLda6qhs\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerLda6qhs\appDevDebugProjectContainer([
    'container.build_hash' => 'Lda6qhs',
    'container.build_id' => '1c52c914',
    'container.build_time' => 1608895687,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLda6qhs');
