<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRp9mvvo\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRp9mvvo/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerRp9mvvo.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerRp9mvvo\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerRp9mvvo\appDevDebugProjectContainer([
    'container.build_hash' => 'Rp9mvvo',
    'container.build_id' => 'a41d676e',
    'container.build_time' => 1609801217,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRp9mvvo');
